name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: ["develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Directory Proyect
      run: cd ./apps/proyecto001

    - name: Install Deps
      run: npm install
      
    - name: Run Test
      run: nx test proyecto001

    - name: Run Build
      run: npm run build --if-present
